### ISSUE TITLE
Could not find the definition for BtsModel

### ISSUE THREAD

**Issue by yingShen-ys** [soyeonm/FILM#1]
Thank you for the great work!

I am walking through the code. And I find that this [line](https://github.com/soyeonm/FILM/blob/d07b6d05f9016d9b780570d1244abbe503fcd8f2/alfred_utils/env/thor_env_code.py#L140) of code created an instance of `BtsModel`. However, I could not find the definition of `BtsModel` anywhere in the repo. 

Could you help me with this? Thank you!

**Comment by soyeonm** [comment]
Hello, sorry for my late reply. I will reply back in a few days!

**Comment by soyeonm** [comment]
Hello,
Sorry for my late reply. https://github.com/soyeonm/FILM/blob/79598779d8373f3cfbc3e969847af30555eb27ea/alfred_utils/env/thor_env_code.py#L122 

This if statement of the code is not used, so BTS model is not used either. Sorry for the confusion!
