### ISSUE TITLE
Sorry my one of my GPU got broken somehow. 

### ISSUE THREAD

**Issue by seongheeHan** [soyeonm/FILM#10]

**Comment by soyeonm** [comment]
Hello,

Sorry for my late reply. You do not have to use multiprocessing and you can use only 1 gpu. From your errors, (looking at the line that has "GetScenesInBuild" in the initialization of the controller), I suspect that your ai2thor version may not be 2.1.0. As far as I remember, "GetScenesInBuild" is not called for controller initialization for ai2thor 2.1.0.

**Comment by seongheeHan** [comment]
Thank you for your kind reply.
It turns out the problem was  detectron2 and the broken GPU. 
It works now thank you.
