### ISSUE TITLE
errors to run main.py

### ISSUE THREAD

**Issue by 1625368821** [soyeonm/FILM#20]
I'm unable to run the main.py code provided in the guide. I followed the guide and tried to run it on a machine  a 8G GPU.

All steps works as expected until I tried to run.I tried for a long time but i couldn't solve the errors.
![image](https://user-images.githubusercontent.com/91419887/191640136-c3517265-a9ca-4080-9907-96e0bdef1962.png)
![image](https://user-images.githubusercontent.com/91419887/191640266-dd9f32b3-4888-493b-b20e-8a435d4852ae.png)

**Comment by soyeonm** [comment]
Hi,
this looks like a dependency error. You can use the docker image I made by trying

`docker pull symin95/combined_alfred_ogn:latest`

as written here: https://github.com/soyeonm/FILM/tree/public/miscellaneous

If you  can't use the docker image itself, I can provide you the dockerfile too.

**Comment by 1625368821** [comment]
I'm sorry I can't use the docker as follow.I will appreciate if you can provide me the dockerfile.
![image](https://user-images.githubusercontent.com/91419887/191645912-fc292f9c-718e-4f4c-a09a-a2fa46732b23.png)

**Comment by 1625368821** [comment]
Hi，I find I can run sudo docker pull symin95/combined_alfred_ogn:latest.Thanks.But I find I have not mang modules after using the docker as follow when I run the main.py.
![image](https://user-images.githubusercontent.com/91419887/191877009-f78d2f42-3ba2-4ccb-bbce-b823cac5d95b.png)
![image](https://user-images.githubusercontent.com/91419887/191876899-1859a306-c3d7-4ff8-9814-b6d3e229bd09.png)

**Comment by soyeonm** [comment]
Hi, In fact there is already the Dockerfile in this repo; but it's likely that you will face dependency errors when you try to build the image. In the meantime, please try the docker image here:
https://hub.docker.com/repository/docker/symin95/may30_gcc_2
as well. 

I will prepare a new dockerfile soon

**Comment by 1625368821** [comment]
Hi,thanks for your reply.And I feel like I can run the main.py.But I find I only have an 8GB GPU that I can use and report the following error.Do you know how to run the main.py without changing the GPU.Thanks again for you reply.
![image](https://user-images.githubusercontent.com/91419887/192956151-3ac1a7dd-0272-49ce-b7aa-e7812bb36926.png)

**Comment by Acejoy** [comment]
> Hi,thanks for your reply.And I feel like I can run the main.py.But I find I only have an 8GB GPU that I can use and report the following error.Do you know how to run the main.py without changing the GPU.Thanks again for you reply. ![image](https://user-images.githubusercontent.com/91419887/192956151-3ac1a7dd-0272-49ce-b7aa-e7812bb36926.png)

Hey, were you able to run the main.py? I have a 4GB GPU myself and I too have the same problem of getting Insufficient GPU memory error. How were you able to bypass this?
